# Módulo Ticker

In [1]:
#

In [2]:
import yfinance as yf

In [3]:
msft = yf.Ticker("MSFT")

In [4]:
# get all stock info
msft.info

{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': ''}

1. **period** : período de dados para download (use o parâmetro period ou use start e end) Os períodos válidos são:
*“ 1d”, “5d”, “1mo”, “3mo”, “6mo”, “1y”, “2y”, “5y”, “10y”, “ytd”, “max”*

2. **interval** : intervalo de dados (dados de 1m estão disponíveis apenas para os últimos 7 dias e intervalo de dados <1d para os últimos 60 dias) Os intervalos válidos são:
*“ 1m”, “2m”, “5m”, “15m”, “30m”, “60m”, “90m”, “1h”, “1d”, “5d”, “1sem”, “1m”, “3m”*

3. **start** : Se não estiver usando ponto – no formato (aaaa-mm-dd) ou datahora.

4. **end** : Se não estiver usando ponto – no formato (aaaa-mm-dd) ou datahora.

5. **prepost** : Incluir dados de mercado pré e pós regulares nos resultados? (O padrão é  False)- geralmente não há necessidade de alterar isso de Falso

6. **auto_adjust** : Ajustar todos os preços OHLC (Open/High/Low/Close) automaticamente? (O padrão é  True) - apenas deixe isso sempre como verdadeiro e não se preocupe com isso

7. **actions** : Baixar eventos de dividendos e desdobramentos de ações? (O padrão é  True)

In [5]:
# get historical market data
hist = msft.history(period="1mo")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-09-28,310.989990,315.480011,309.450012,313.640015,19683600,0,0
2023-09-29,317.750000,319.470001,314.980011,315.750000,24140300,0,0
2023-10-02,316.279999,321.890015,315.179993,321.799988,20570000,0,0
2023-10-03,320.829987,321.390015,311.209991,313.390015,21033500,0,0
2023-10-04,314.029999,320.040009,314.000000,318.959991,20720100,0,0
2023-10-05,319.089996,319.980011,314.899994,319.359985,16965600,0,0
2023-10-06,316.549988,329.190002,316.299988,327.260010,25645500,0,0
2023-10-09,324.750000,330.299988,323.179993,329.820007,19891200,0,0
2023-10-10,330.959991,331.100006,327.670013,328.390015,20557100,0,0
2023-10-11,331.209991,332.820007,329.140015,332.420013,20063200,0,0
2023-10-12,330.570007,333.630005,328.720001,331.160004,19313100,0,0
2023-10-13,332.380005,333.829987,326.359985,327.730011,21072400,0,0
2023-10-16,331.049988,336.140015,330.600006,332.640015,22158000,0,0
2023-10-17,329.589996,333.459991,327.410004,332.059998,18338500,0,0
2023-10-18,332.489990,335.589996,328.299988,330.109985,23153600,0,0
2023-10-19,332.149994,336.880005,330.910004,331.320007,25052100,0,0
2023-10-20,331.720001,331.920013,325.450012,326.670013,25012600,0,0
2023-10-23,325.470001,332.730011,324.390015,329.320007,24374700,0,0
2023-10-24,331.299988,331.839996,327.600006,330.529999,31153600,0,0
2023-10-25,345.019989,346.200012,337.619995,340.670013,55053800,0,0
2023-10-26,340.540009,341.630005,326.940002,327.890015,37828500,0,0
2023-10-27,330.429993,336.720001,328.399994,329.809998,29835200,0,0

In [7]:
# show actions (dividends, splits, capital gains)
msft.actions

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []

In [8]:
msft.dividends

Series([], Name: Dividends, dtype: int64)

In [9]:
msft.splits

Series([], Name: Stock Splits, dtype: int64)

In [10]:
msft.capital_gains  # only for mutual funds & etfs

AttributeError: 'Ticker' object has no attribute 'capital_gains'

In [11]:
# show share count
msft.get_shares_full(start="2022-01-01", end=None)

AttributeError: 'Ticker' object has no attribute 'get_shares_full'

In [12]:
# show financials:
msft.income_stmt

AttributeError: 'Ticker' object has no attribute 'income_stmt'

In [13]:
# - income statement
msft.quarterly_income_stmt

AttributeError: 'Ticker' object has no attribute 'quarterly_income_stmt'

In [14]:
# - balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet
# - cash flow statement
msft.cashflow
msft.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [15]:
# show holders
msft.major_holders
msft.institutional_holders
msft.mutualfund_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Total Stock Market Index Fund,231883087,2023-06-29,0.0312,76477360357
1,Vanguard 500 Index Fund,177034936,2023-06-29,0.0238,58387891809
2,Fidelity 500 Index Fund,83296877,2023-05-30,0.0112,27472142800
3,SPDR S&P 500 ETF Trust,83514381,2023-09-29,0.0112,27543877793
4,iShares Core S&P 500 ETF,70264910,2023-09-29,0.0095,23174069795
5,Vanguard Growth Index Fund,63262454,2023-06-29,0.0085,20864589799
6,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",58757680,2023-08-30,0.0079,19378870297
7,Vanguard Institutional Index Fund-Institutiona...,50756950,2023-06-29,0.0068,16740149555
8,Growth Fund Of America Inc,39310503,2023-09-29,0.0053,12964996898
9,Vanguard Information Technology Index Fund,37650593,2023-05-30,0.0051,12417541985

In [16]:
# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

AttributeError: 'Ticker' object has no attribute 'earnings_dates'

In [17]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

'US5949181045'

In [18]:
# show options expirations
msft.options

('2023-11-03',
 '2023-11-10',
 '2023-11-17',
 '2023-11-24',
 '2023-12-01',
 '2023-12-08',
 '2023-12-15',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-05-17',
 '2024-06-21',
 '2024-09-20',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-12-19',
 '2026-01-16')

In [19]:
# show news
msft.news

[{'uuid': '21852c5b-4482-359c-a629-228906af0792',
  'title': 'Dow Jones Futures Due With Apple, Fed Ahead; Microsoft Leads Stocks Near Buy Points',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/21852c5b-4482-359c-a629-228906af0792/dow-jones-futures-due-with.html',
  'providerPublishTime': 1698611700,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Mh5wPBSgCgrhU_sZir9mfQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/4ee1f3d52d02c38decccf8c54661a8ca',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/_caRpf8qzn92aZmtWpPauQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/4ee1f3d52d02c38decccf8c54661a8ca',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT',
   'COMP',
   'AMZN',
   '^DJI',
   '^GSPC',
   'META',
   'AAPL',
   'NOW']},
 {'uuid': '94b539ed-c77f-3e40-8980-fadf7db36394',
  'title': '1 Green Flag for Alphabet in 2023, and 1 Red Flag',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/94b539ed-c77f-3e40-8980-fadf7db36394/1-green-flag-for-alphabet-in.html',
  'providerPublishTime': 1698598800,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/dZUhzOgiZUS6xgjtgvlFTQ--~B/aD0yMjUwO3c9NDAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/0b96e623d2ab93ff929fa4dfd10477db',
     'width': 4000,
     'height': 2250,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/b5.R1C4.Y7sM4ACICu3i2g--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/0b96e623d2ab93ff929fa4dfd10477db',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOGL', 'MSFT']},
 {'uuid': 'fe26c5e7-6e8d-3384-86ff-1ceb051292ea',
  'title': "Qualcomm Is Gunning for a Piece of Intel's Lunch -- Time to Buy Qualcomm Stock?",
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/fe26c5e7-6e8d-3384-86ff-1ceb051292ea/qualcomm-is-gunning-for-a.html',
  'providerPublishTime': 1698597000,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/5qSWyH4iGjnujAZa1IrXpg--~B/aD01MzA0O3c9Nzk1MjthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/f1baa443e3dc7743b478d7cd7d690151',
     'width': 7952,
     'height': 5304,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/.ses19i5TixlxHdeGcx6_g--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/f1baa443e3dc7743b478d7cd7d690151',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['QCOM', 'INTC', 'AAPL', 'MSFT']},
 {'uuid': '817ac1d2-9c20-426f-b777-b847826f13eb',
  'title': 'Fed meeting, Apple earnings: What to know this week',
  'publisher': 'Yahoo Finance',
  'link': 'https://finance.yahoo.com/news/fed-meeting-apple-earnings-what-to-know-this-week-140035960.html',
  'providerPublishTime': 1698588017,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/V9IDB0OWcVu6lVHagwJRXg--~B/aD0zNjc4O3c9NTUwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-06/ec26b080-055d-11ee-b3de-b762ae81496f',
     'width': 5500,
     'height': 3678,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/wcAPgDcus8nbj_0cFNXe.w--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2023-06/ec26b080-055d-11ee-b3de-b762ae81496f',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AMZN',
   'PFE',
   'META',
   'MSFT',
   'ABNB',
   'MCD',
   'GOOG',
   'AAPL',
   'AMD',
   '^DJI',
   'CAT']},
 {'uuid': '76c699c8-0560-4271-9831-1bdd6d079e30',
  'title': "The Nasdaq's fallen into a correction –\xa0what investors should consider",
  'publisher': 'Yahoo Finance',
  'link': 'https://finance.yahoo.com/news/the-nasdaqs-fallen-into-a-correction--what-investors-should-consider-123057423.html',
  'providerPublishTime': 1698582657,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/jw9RWLwQjomJqqixAFW5JA--~B/aD00NjAwO3c9NjkwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2023-10/7a02bea0-7514-11ee-9b7e-db35a15f3e64',
     'width': 6900,
     'height': 4600,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/zw7jzDtq.IxCvKrgw2e8Ww--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2023-10/7a02bea0-7514-11ee-9b7e-db35a15f3e64',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOG', 'AAPL', 'TSLA', 'MSFT', 'AMZN', 'META', 'NVDA']},
 {'uuid': '27f7d46c-d0ff-36a8-8b79-e369008ee5e2',
  'title': 'Amazon And Intel Just Showed the Cloud Industry Is Turning Around',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/27f7d46c-d0ff-36a8-8b79-e369008ee5e2/amazon-and-intel-just-showed.html',
  'providerPublishTime': 1698581100,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/tXlDnd17dxbvMpp4dUBS.A--~B/aD0zMDAwO3c9NDgwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/0ef2280f282790327df539cf27469004',
     'width': 4800,
     'height': 3000,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/WriGXbqeGxnWWAW2qzGekQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/0ef2280f282790327df539cf27469004',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['INTC', 'AMZN', 'GOOGL', 'MSFT']},
 {'uuid': 'cb354b51-f1fc-3a07-8bd4-bfbe4a9aa031',
  'title': 'Big Bank Bought Up Apple, Tesla, AT&T, and Microsoft Stock',
  'publisher': 'Barrons.com',
  'link': 'https://finance.yahoo.com/m/cb354b51-f1fc-3a07-8bd4-bfbe4a9aa031/big-bank-bought-up-apple%2C.html',
  'providerPublishTime': 1698580800,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/JfAqIyPn9UErPHcdO6BuDQ--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/c7f38aef47eb5584b5ef1ee2a1e90221',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/eK6_YxF.oWa95xYyOcmvjw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/c7f38aef47eb5584b5ef1ee2a1e90221',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['T', 'TSLA', 'MSFT', 'AAPL']},
 {'uuid': 'cf6e3f45-ea21-32a9-a86e-07281f1a6c18',
  'title': 'The Best Stocks to Invest $1,000 in Right Now',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/cf6e3f45-ea21-32a9-a86e-07281f1a6c18/the-best-stocks-to-invest.html',
  'providerPublishTime': 1698580380,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/EHNirwbtofSjHnGVYqGqQA--~B/aD0xNDE0O3c9MjEyMTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/d5f1de061842dc45af0358318fdbe1c5',
     'width': 2121,
     'height': 1414,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/_n73jDrzhb5ThkyoOV2kxw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/d5f1de061842dc45af0358318fdbe1c5',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'DDOG']}]

In [20]:
# get option chain for specific expiration
opt = msft.option_chain('2023-07-21')
# data available via: opt.calls, opt.puts
opt.calls

ValueError: Expiration `2023-07-21` cannot be found. Available expiration are: [2023-11-03, 2023-11-10, 2023-11-17, 2023-11-24, 2023-12-01, 2023-12-08, 2023-12-15, 2024-01-19, 2024-02-16, 2024-03-15, 2024-04-19, 2024-05-17, 2024-06-21, 2024-09-20, 2024-12-20, 2025-01-17, 2025-06-20, 2025-12-19, 2026-01-16]

In [24]:
opt.puts

NameError: name 'opt' is not defined

# Multiple tickers

In [25]:
tickers = yf.Tickers('msft aapl goog')
# access each ticker using (example)
tickers.tickers['MSFT'].info

KeyboardInterrupt:

In [ ]:
tickers.tickers['AAPL'].history(period="1mo")

In [ ]:
tickers.tickers['GOOG'].actions

# Pandas Datareader

In [26]:
from pandas_datareader import data as pdr

In [27]:
import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

In [28]:
# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")

[*********************100%***********************]  1 of 1 completed

In [29]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-01-03,225.039993,225.830002,223.880005,225.240005,200.629684,91366500
2017-01-04,225.619995,226.750000,225.610001,226.580002,201.823257,78744400
2017-01-05,226.270004,226.580002,225.479996,226.399994,201.662949,78379000
2017-01-06,226.529999,227.750000,225.899994,227.210007,202.384430,71559900
2017-01-09,226.910004,227.070007,226.419998,226.460007,201.716400,46939700
...,...,...,...,...,...,...
2017-04-24,237.179993,237.410004,234.559998,237.169998,212.175247,119209900
2017-04-25,237.910004,238.949997,237.809998,238.550003,213.409836,76698300
2017-04-26,238.509995,239.529999,238.350006,238.399994,213.275635,84702500
2017-04-27,238.770004,238.949997,237.979996,238.600006,213.454544,57410300
2017-04-28,238.899994,238.929993,237.929993,238.080002,212.989349,63532800

# Teste Bitcoin BTC-USD

In [30]:
btc = yf.Ticker("BTC-USD")

In [31]:
btc.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-09-29,27024.841797,27225.937500,26721.763672,26911.720703,10396435377,0,0
2023-09-30,26911.689453,27091.794922,26888.968750,26967.916016,5331172801,0,0
2023-10-01,26967.396484,28047.238281,26965.093750,27983.750000,9503917434,0,0
2023-10-02,27976.798828,28494.458984,27347.787109,27530.785156,19793041322,0,0
2023-10-03,27508.251953,27667.191406,27216.001953,27429.978516,11407814187,0,0
2023-10-04,27429.074219,27826.658203,27248.105469,27799.394531,11143355314,0,0
2023-10-05,27798.646484,28091.861328,27375.601562,27415.912109,11877253670,0,0
2023-10-06,27412.123047,28252.537109,27215.552734,27946.597656,13492391599,0,0
2023-10-07,27946.781250,28028.091797,27870.423828,27968.839844,6553044316,0,0
2023-10-08,27971.677734,28102.169922,27740.662109,27935.089844,7916875290,0,0
2023-10-09,27934.472656,27989.470703,27302.562500,27583.677734,12007668568,0,0
2023-10-10,27589.201172,27715.847656,27301.654297,27391.019531,9973350678,0,0
2023-10-11,27392.076172,27474.115234,26561.099609,26873.320312,13648094333,0,0
2023-10-12,26873.292969,26921.439453,26558.320312,26756.798828,9392909295,0,0
2023-10-13,26752.878906,27092.697266,26686.322266,26862.375000,15165312851,0,0
2023-10-14,26866.203125,26969.000000,26814.585938,26861.707031,5388116782,0,0
2023-10-15,26858.011719,27289.169922,26817.894531,27159.652344,7098201980,0,0
2023-10-16,27162.628906,29448.138672,27130.472656,28519.466797,27833876539,0,0
2023-10-17,28522.097656,28618.751953,28110.185547,28415.748047,14872527508,0,0
2023-10-18,28413.531250,28889.009766,28174.251953,28328.341797,12724128586,0,0
2023-10-19,28332.416016,28892.474609,28177.988281,28719.806641,14448058195,0,0
2023-10-20,28732.812500,30104.085938,28601.669922,29682.949219,21536125230,0,0
2023-10-21,29683.380859,30287.482422,29481.751953,29918.412109,11541146996,0,0
2023-10-22,29918.654297,30199.433594,29720.312500,29993.896484,10446520040,0,0
2023-10-23,30140.685547,34370.437500,30097.828125,33086.234375,38363572311,0,0
2023-10-24,33077.304688,35150.433594,32880.761719,33901.527344,44934999645,0,0
2023-10-25,33916.042969,35133.757812,33709.109375,34502.820312,25254318008,0,0
2023-10-26,34504.289062,34832.910156,33762.324219,34156.648438,19427195376,0,0
2023-10-27,34156.500000,34238.210938,33416.886719,33909.800781,16418032871,0,0
2023-10-28,33907.722656,34399.390625,33874.804688,34089.574219,10160330825,0,0
2023-10-29,34089.371094,34736.917969,33947.566406,34559.761719,10501677056,0,0

In [32]:
# Import packages
import yfinance as yf
import pandas as pd

# Read and print the stock tickers that make up S&P500
tickers = pd.read_html(
    'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]
print(tickers.head())

# Get the data for this tickers from yahoo finance
data = yf.download(tickers.Symbol.to_list(),'2023-1-1','2023-10-10', auto_adjust=True)['Close']
print(data.head())

  Symbol     Security             GICS Sector               GICS Sub-Industry  \
0    MMM           3M             Industrials        Industrial Conglomerates
1    AOS  A. O. Smith             Industrials               Building Products
2    ABT       Abbott             Health Care           Health Care Equipment
3   ABBV       AbbVie             Health Care                 Pharmaceuticals
4    ACN    Accenture  Information Technology  IT Consulting & Other Services

     Headquarters Location  Date added      CIK      Founded
0    Saint Paul, Minnesota  1957-03-04    66740         1902
1     Milwaukee, Wisconsin  2017-07-26    91142         1916
2  North Chicago, Illinois  1957-03-04     1800         1888
3  North Chicago, Illinois  2012-12-31  1551152  2013 (1888)
4          Dublin, Ireland  2011-07-06  1467373         1989
[**********************46%                       ]  229 of 503 completed

KeyboardInterrupt:

In [ ]:
tickers.tickers['NYSE Arca GLD'].history(period="1mo")

In [34]:
GLD = yf.Ticker("GLD")

In [36]:
GLD.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-09-28,173.910004,174.139999,172.320007,173.229996,10061900,0,0
2023-09-29,173.919998,174.029999,171.270004,171.449997,10424900,0,0
2023-10-02,170.229996,170.460007,169.500000,169.649994,12706000,0,0
2023-10-03,169.139999,170.080002,168.750000,169.160004,11459800,0,0
2023-10-04,169.210007,169.410004,168.500000,169.139999,10034600,0,0
2023-10-05,168.740005,169.000000,168.300003,168.830002,6970200,0,0
2023-10-06,169.169998,170.229996,168.500000,169.699997,9942200,0,0
2023-10-09,171.179993,172.860001,171.080002,172.820007,10201500,0,0
2023-10-10,172.080002,172.800003,171.899994,172.529999,5844000,0,0
2023-10-11,173.600006,174.130005,173.259995,173.789993,7128000,0,0
2023-10-12,174.059998,174.229996,173.240005,173.259995,5912700,0,0
2023-10-13,176.889999,179.100006,176.720001,178.830002,18796500,0,0
2023-10-16,177.839996,178.330002,177.539993,177.960007,8385400,0,0
2023-10-17,178.369995,179.130005,177.979996,178.289993,8231900,0,0
2023-10-18,180.889999,182.020004,179.750000,180.869995,13920800,0,0
2023-10-19,181.039993,183.429993,180.820007,183.089996,13406600,0,0
2023-10-20,183.429993,185.229996,183.089996,183.589996,12782800,0,0
2023-10-23,183.509995,183.559998,182.710007,182.970001,9479800,0,0
2023-10-24,182.070007,183.399994,181.679993,182.949997,6594000,0,0
2023-10-25,183.419998,184.300003,182.039993,183.720001,10087000,0,0
2023-10-26,183.399994,184.490005,182.869995,184.009995,7671400,0,0
2023-10-27,183.759995,186.360001,183.470001,186.149994,14095600,0,0

In [38]:
ETH = yf.Ticker("ETH-USD")
ETH.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-09-29,1652.999878,1687.281250,1648.656494,1667.943848,5529687537,0,0
2023-09-30,1667.834473,1692.531128,1666.563843,1671.161865,3155292192,0,0
2023-10-01,1671.161499,1750.595703,1670.082153,1733.810425,5054880180,0,0
2023-10-02,1732.984009,1743.563599,1646.077637,1663.627563,8420552922,0,0
2023-10-03,1662.887207,1670.356323,1644.496460,1656.685669,4742827302,0,0
2023-10-04,1656.735962,1657.253540,1629.426636,1647.838135,5127524863,0,0
2023-10-05,1647.788208,1654.379028,1609.849976,1611.476440,5403759057,0,0
2023-10-06,1611.365723,1659.609863,1611.365723,1645.831543,4941208729,0,0
2023-10-07,1645.810913,1648.183716,1631.158203,1634.511230,2578994988,0,0
2023-10-08,1634.657349,1641.182373,1618.189209,1633.548584,3315554175,0,0
2023-10-09,1633.454834,1635.447876,1553.006958,1579.806641,7020801716,0,0
2023-10-10,1580.112061,1593.741333,1553.031738,1567.713013,5254966125,0,0
2023-10-11,1567.680786,1578.223511,1548.980469,1566.254761,5416504273,0,0
2023-10-12,1566.355957,1566.878174,1523.237549,1539.612427,5003930677,0,0
2023-10-13,1539.432861,1571.750610,1537.921143,1552.089478,4575141511,0,0
2023-10-14,1552.263794,1560.325073,1545.738770,1555.256836,2429214718,0,0
2023-10-15,1555.076050,1565.760864,1550.554565,1558.069824,2923337883,0,0
2023-10-16,1558.313477,1628.156250,1555.989624,1600.534302,8846928526,0,0
2023-10-17,1600.635620,1601.294678,1554.402954,1565.439575,5032686973,0,0
2023-10-18,1565.382812,1584.726929,1556.736328,1563.749878,4354138855,0,0
2023-10-19,1563.958130,1573.737671,1543.585083,1567.457031,5035110867,0,0
2023-10-20,1567.570923,1628.609009,1562.302856,1604.666870,6747486127,0,0
2023-10-21,1604.822266,1641.241821,1593.447998,1629.304443,4212179634,0,0
2023-10-22,1629.297729,1667.666626,1623.984741,1663.429932,5248406817,0,0
2023-10-23,1674.849243,1794.070435,1663.447998,1765.382690,14362295879,0,0
2023-10-24,1766.014648,1852.684448,1758.690063,1784.437500,15888690475,0,0
2023-10-25,1784.905029,1814.484741,1762.147095,1787.397583,9439066475,0,0
2023-10-26,1787.481934,1865.095215,1764.013062,1804.039307,11196672635,0,0
2023-10-27,1803.794922,1804.135864,1751.440063,1780.045288,7493399771,0,0
2023-10-28,1780.084229,1800.605347,1773.436646,1776.618164,4226112731,0,0
2023-10-29,1776.563965,1806.743652,1768.306274,1794.358154,4216801280,0,0

In [ ]:
ETH = yf.Ticker("ETH")